version: '3'

services:
  backend:
    build: .
    ports:
      - '3001:3000'
    environment:
      - NEO4J_URI_STAGING=neo4j://stg-drug-neo4j.manageai.co.th:37687
      - NEO4J_USERNAME_STAGING=neo4j
      - NEO4J_PASSWORD_STAGING=qn3qz7jB0GIE3PZWSjWnoibUy4DP8ue8
      - ELASTIC_URL=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elasticpassword
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=elasticpassword
    ports:
      - '9200:9200'
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - elasticsearch.username=elastic
      - elasticsearch.password=elasticpassword
      - ELASTICSEARCH_SERVICE_ACCOUNT_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2RlZmF1bHQ6RzdPaS10UUhSbUdIekF0RWxLN2VXUQ
      - XPACK_FLEET_ENABLED=false
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=zk5azan32nmkssnt2a7vkdnie9gok5eu
      - XPACK_REPORTING_ENCRYPTIONKEY=65x5sdwdpqew1vbr9mqlpxignmu7ssnh
      - XPACK_SECURITY_ENCRYPTIONKEY=vmj89waw7pcir6iddqb1rm5ye8pwvge7
      
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

volumes:
  es_data:
